/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mini_project;

import javax.swing.JOptionPane;

/**
 *
 * @author Amrutha
 */
public class Menu3 extends javax.swing.JFrame {

    /**
     * Creates new form Menu3
     */
    private String Mn_uname;
    private int ord=0,ct1,ct2,ct3,ct4;
    public Menu3() {
        initComponents();
    }
    public Menu3(String uname) {
        initComponents();
        Mn_uname=uname;
    }
    private String rname,uname;
    private int order,update;
    public Menu3(String Runame,int orde,int updat,String unam) {
        initComponents();
        rname=Runame;
        order=orde;
        update=updat;
        uname=unam; 
    }
    public Menu3(int od,int c1,int c2,int c3,int c4) {
        initComponents();
        ord=od;
        ct1=c1;
        ct2=c2;
        ct3=c3;
        ct4=c4;
        if(ct1>=1)
            Cnt1.setText(String.valueOf(ct1));
        if(ct2>=1)
            Cnt2.setText(String.valueOf(ct2));
        if(ct3>=1)
            Cnt3.setText(String.valueOf(ct3));
        if(ct4>=1)
            Cnt4.setText(String.valueOf(ct4));
        
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Dish1 = new javax.swing.JLabel();
        Price1 = new javax.swing.JLabel();
        Price2 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        Dish3 = new javax.swing.JLabel();
        Price3 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        Dish2 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        Dish4 = new javax.swing.JLabel();
        Price4 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        Cnt1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Cnt2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Cnt3 = new javax.swing.JLabel();
        Cnt4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Verdana", 3, 34)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Bon Appetit");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 46, 260, 36));

        Dish1.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        Dish1.setForeground(new java.awt.Color(255, 255, 255));
        Dish1.setText("Pasta Carbonara");
        jPanel2.add(Dish1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 149, 150, 32));

        Price1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        Price1.setForeground(new java.awt.Color(255, 255, 255));
        Price1.setText("35");
        jPanel2.add(Price1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, 20));

        Price2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        Price2.setForeground(new java.awt.Color(255, 255, 255));
        Price2.setText("55");
        jPanel2.add(Price2, new org.netbeans.lib.awtextra.AbsoluteConstraints(855, 210, 28, -1));

        jButton9.setText("+");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 260, 50, -1));

        jButton10.setText(" -");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 539, 50, -1));

        Dish3.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        Dish3.setForeground(new java.awt.Color(255, 255, 255));
        Dish3.setText(" Baked Lasagna");
        jPanel2.add(Dish3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 429, 140, 32));

        Price3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        Price3.setForeground(new java.awt.Color(255, 255, 255));
        Price3.setText("110");
        jPanel2.add(Price3, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 476, 34, 25));

        jButton11.setText(" +");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 539, 50, -1));

        jButton12.setText(" -");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(828, 264, 46, -1));

        Dish2.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        Dish2.setForeground(new java.awt.Color(255, 255, 255));
        Dish2.setText("Herbed Gnocchi");
        jPanel2.add(Dish2, new org.netbeans.lib.awtextra.AbsoluteConstraints(824, 149, 150, 32));

        jButton13.setText(" +");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(939, 264, 50, -1));

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mini_project/pasta car.jpg"))); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 149, 210, 144));

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mini_project/Crispy-Garlic-Butter-Herbed-Gnocchi1.jpg"))); // NOI18N
        jPanel2.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 149, 210, 144));

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mini_project/la.jpg"))); // NOI18N
        jPanel2.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 429, 210, 138));

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mini_project/spa.jpg"))); // NOI18N
        jPanel2.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 429, 210, 138));

        Dish4.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        Dish4.setForeground(new java.awt.Color(255, 255, 255));
        Dish4.setText("Spaghetti");
        jPanel2.add(Dish4, new org.netbeans.lib.awtextra.AbsoluteConstraints(828, 429, 90, 32));

        Price4.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        Price4.setForeground(new java.awt.Color(255, 255, 255));
        Price4.setText("110");
        jPanel2.add(Price4, new org.netbeans.lib.awtextra.AbsoluteConstraints(859, 479, 39, 25));

        jButton20.setText(" +");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(939, 537, 50, -1));

        jButton23.setText("-");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 261, 50, -1));

        Cnt1.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        Cnt1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(Cnt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 260, 40, 30));

        jButton1.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jButton1.setText("NEXT");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(916, 699, -1, -1));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1009, 360, 43, 29));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Rs.");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, 20));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Rs.");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(824, 213, -1, -1));

        Cnt2.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        Cnt2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(Cnt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 264, 36, 29));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Rs.");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 479, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Rs.");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(828, 482, -1, -1));

        Cnt3.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        Cnt3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(Cnt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 539, 50, 30));

        Cnt4.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        Cnt4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(Cnt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(886, 538, 47, 28));

        jButton3.setText(" -");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(828, 538, 52, -1));

        jButton4.setBackground(new java.awt.Color(153, 102, 0));
        jButton4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton4.setText("X");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 20, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mini_project/b0.jpg"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 780));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed
    private int count1=0,count2=0,count3=0,count4=0;
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        
        if(count1<=9)
        {
            count1++;
            Cnt1.setText(""+count1+"");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        
        if(count1>=1)
        {
            count1--;
            Cnt1.setText(""+count1+"");
        } 
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(Cnt1.getText().isEmpty() && Cnt2.getText().isEmpty() && Cnt3.getText().isEmpty() && Cnt4.getText().isEmpty() )
        {
           JOptionPane.showMessageDialog(null, "Please select atleast one dish"); 
        }
        else{
        if(update==1)
        {
            new CART_Update(order,"R04",Mn_uname,Dish1.getText(),Cnt1.getText(),Price1.getText(),Dish2.getText(),Cnt2.getText(),Price2.getText(),Dish3.getText(),Cnt3.getText(),Price3.getText(),Dish4.getText(),Cnt4.getText(),Price4.getText()).setVisible(true);
            this.dispose();
        }
        else
        {
            new CART(ord,"R04",Mn_uname,Dish1.getText(),Cnt1.getText(),Price1.getText(),Dish2.getText(),Cnt2.getText(),Price2.getText(),Dish3.getText(),Cnt3.getText(),Price3.getText(),Dish4.getText(),Cnt4.getText(),Price4.getText()).setVisible(true);
            this.dispose();
        }
        }
                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
         if(count2<=9)
        {
            count2++;
            Cnt2.setText(""+count2+"");
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
         if(count2>=1)
        {
            count2--;
            Cnt2.setText(""+count2+"");
        } 
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        if(count3>=1)
        {
            count3--;
            Cnt3.setText(""+count3+"");
        } 
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
         if(count3<=9)
        {
            count3++;
            Cnt3.setText(""+count3+"");
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(count4>=1)
        {
            count4--;
            Cnt4.setText(""+count4+"");
        } 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        if(count4<=9)
        {
            count4++;
            Cnt4.setText(""+count4+"");
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cnt1;
    private javax.swing.JLabel Cnt2;
    private javax.swing.JLabel Cnt3;
    private javax.swing.JLabel Cnt4;
    private javax.swing.JLabel Dish1;
    private javax.swing.JLabel Dish2;
    private javax.swing.JLabel Dish3;
    private javax.swing.JLabel Dish4;
    private javax.swing.JLabel Price1;
    private javax.swing.JLabel Price2;
    private javax.swing.JLabel Price3;
    private javax.swing.JLabel Price4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
