/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mini_project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Amrutha
 */
public class menu2 extends javax.swing.JFrame {

    /**
     * Creates new form menu2
     */
   private String Mn_uname;
   private int ord=0,ct1,ct2,ct3,ct4;
    public menu2() {
        initComponents();
    }
    public menu2(String uname) {
        initComponents();
        Mn_uname=uname;
    }
    private String rname,uname;
    private int order,update;
    public menu2(String Runame,int orde,int updat,String unam) {
        initComponents();
        rname=Runame;
        order=orde;
        update=updat;
        uname=unam; 
    
    }
    public menu2(int od,int c1,int c2,int c3,int c4) {
        initComponents();
        ord=od;
        ct1=c1;
        ct2=c2;
        ct3=c3;
        ct4=c4;
        if(ct1>=1)
            Cnt1.setText(String.valueOf(ct1));
        if(ct2>=1)
            Cnt2.setText(String.valueOf(ct2));
        if(ct3>=1)
            Cnt3.setText(String.valueOf(ct3));
        if(ct4>=1)
            Cnt4.setText(String.valueOf(ct4));
       
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Cnt1 = new javax.swing.JLabel();
        Price2 = new javax.swing.JLabel();
        Price1 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        Cnt3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        Dish4 = new javax.swing.JLabel();
        Price3 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        Dish1 = new javax.swing.JLabel();
        Dish2 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        Dish3 = new javax.swing.JLabel();
        Price4 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Cnt2 = new javax.swing.JLabel();
        Cnt4 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Verdana", 3, 34)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Dawat");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 160, 36));

        Cnt1.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        Cnt1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(Cnt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 243, 45, 29));

        Price2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        Price2.setForeground(new java.awt.Color(255, 255, 255));
        Price2.setText("35");
        jPanel2.add(Price2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 184, -1, 25));

        Price1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        Price1.setForeground(new java.awt.Color(255, 255, 255));
        Price1.setText("55");
        jPanel2.add(Price1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 29, -1));

        jButton9.setText(" -");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 243, 44, -1));

        Cnt3.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        Cnt3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(Cnt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 544, 39, 29));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Rs.");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 489, -1, 25));

        jButton10.setText(" -");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 544, 45, -1));

        Dish4.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        Dish4.setForeground(new java.awt.Color(255, 255, 255));
        Dish4.setText("Egg Biryani");
        jPanel2.add(Dish4, new org.netbeans.lib.awtextra.AbsoluteConstraints(793, 434, 105, 32));

        Price3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        Price3.setForeground(new java.awt.Color(255, 255, 255));
        Price3.setText("70");
        jPanel2.add(Price3, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 489, -1, 25));

        jButton11.setText(" +");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 544, 50, -1));

        jButton12.setText(" +");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 243, 50, -1));

        Dish1.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        Dish1.setForeground(new java.awt.Color(255, 255, 255));
        Dish1.setText("Chicken Lolipop");
        jPanel2.add(Dish1, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 128, -1, 32));

        Dish2.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        Dish2.setForeground(new java.awt.Color(255, 255, 255));
        Dish2.setText("Fish Fry");
        jPanel2.add(Dish2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 130, -1, 32));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Rs.");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(784, 179, -1, 35));

        jButton13.setText(" -");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(784, 243, 50, -1));

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mini_project/lol.jpg"))); // NOI18N
        jPanel2.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 128, 210, 144));

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mini_project/fifr.jpg"))); // NOI18N
        jPanel2.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 134, 200, 138));

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mini_project/egg.jpg"))); // NOI18N
        jPanel2.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 434, 202, 138));

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mini_project/pra.jpg"))); // NOI18N
        jPanel2.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 435, 210, 138));

        Dish3.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        Dish3.setForeground(new java.awt.Color(255, 255, 255));
        Dish3.setText("Prawns Manchurian");
        jPanel2.add(Dish3, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 432, -1, 32));

        Price4.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        Price4.setForeground(new java.awt.Color(255, 255, 255));
        Price4.setText("110");
        jPanel2.add(Price4, new org.netbeans.lib.awtextra.AbsoluteConstraints(824, 490, -1, 25));

        jButton20.setText(" +");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(875, 243, 50, -1));

        jButton1.setText(" +");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(875, 543, 50, -1));

        jButton2.setText(" -");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(784, 543, 50, -1));

        jButton3.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        jButton3.setText("NEXT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(853, 685, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Rs.");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        Cnt2.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        Cnt2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(Cnt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(833, 243, 36, 29));

        Cnt4.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        Cnt4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(Cnt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(833, 543, 36, 25));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Rs.");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(793, 493, -1, -1));

        jButton5.setBackground(new java.awt.Color(102, 0, 0));
        jButton5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("X");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mini_project/bg234.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 790));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
         if(count1>=1)
        {
            count1--;
            Cnt1.setText(""+count1+"");
        } 
        
    }//GEN-LAST:event_jButton9ActionPerformed
    private int count1=0,count2=0,count3=0,count4=0;
    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
         if(count2>=1)
        {
            count2--;
            Cnt2.setText(""+count2+"");
        } 
         
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
          if(count3>=1)
        {
            count3--;
            Cnt3.setText(""+count3+"");
        } 
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          if(count4>=1)
        {
            count4--;
            Cnt4.setText(""+count4+"");
        } 
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
         if(count1<=9)
        {
            count1++;
            Cnt1.setText(""+count1+"");
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        if(count2<=9)
        {
            count2++;
            Cnt2.setText(""+count2+"");
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
         if(count3<=9)
        {
            count3++;
            Cnt3.setText(""+count3+"");
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         if(count4<=9)
        {
            count4++;
            Cnt4.setText(""+count4+"");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(Cnt1.getText().isEmpty() && Cnt2.getText().isEmpty() && Cnt3.getText().isEmpty() && Cnt4.getText().isEmpty() )
        {
           JOptionPane.showMessageDialog(null, "Please select atleast one dish"); 
        }
        else{
         if(update==1)
        {
            new CART_Update(order,"R02",Mn_uname,Dish1.getText(),Cnt1.getText(),Price1.getText(),Dish2.getText(),Cnt2.getText(),Price2.getText(),Dish3.getText(),Cnt3.getText(),Price3.getText(),Dish4.getText(),Cnt4.getText(),Price4.getText()).setVisible(true);
            this.dispose();
        }
        else
        {
            new CART(ord,"R02",Mn_uname,Dish1.getText(),Cnt1.getText(),Price1.getText(),Dish2.getText(),Cnt2.getText(),Price2.getText(),Dish3.getText(),Cnt3.getText(),Price3.getText(),Dish4.getText(),Cnt4.getText(),Price4.getText()).setVisible(true);
            this.dispose();
        }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cnt1;
    private javax.swing.JLabel Cnt2;
    private javax.swing.JLabel Cnt3;
    private javax.swing.JLabel Cnt4;
    private javax.swing.JLabel Dish1;
    private javax.swing.JLabel Dish2;
    private javax.swing.JLabel Dish3;
    private javax.swing.JLabel Dish4;
    private javax.swing.JLabel Price1;
    private javax.swing.JLabel Price2;
    private javax.swing.JLabel Price3;
    private javax.swing.JLabel Price4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
