/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mini_project;

import javax.swing.JOptionPane;

/**
 *
 * @author Amrutha
 */
public class menu1 extends javax.swing.JFrame {

    /**
     * Creates new form menu1
     */
    private String Mn_uname;
    private int ord=0,ct1,ct2,ct3,ct4;
    public menu1() {
        initComponents();
    }
    public menu1(String uname) {
        initComponents();
        Mn_uname=uname;
    }
    private String rname,uname;
    private int order,update;
    public menu1(String Runame,int orde,int updat,String unam) {
        initComponents();
        rname=Runame;
        order=orde;
        update=updat;
        uname=unam; 
        //System.out.println(uname);
    }
    public menu1(int od,int c1,int c2,int c3,int c4) {
        initComponents();
        ord=od;
        ct1=c1;
        ct2=c2;
        ct3=c3;
        ct4=c4;
         if(ct1>=1)
            Cnt1.setText(String.valueOf(ct1));
        if(ct2>=1)
            Cnt2.setText(String.valueOf(ct2));
        if(ct3>=1)
            Cnt3.setText(String.valueOf(ct3));
        if(ct4>=1)
            Cnt4.setText(String.valueOf(ct4));
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Dish1 = new javax.swing.JLabel();
        Price1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        Dish3 = new javax.swing.JLabel();
        Price3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        Dish4 = new javax.swing.JLabel();
        Cnt3 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        Cnt1 = new javax.swing.JLabel();
        Price2 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        Price4 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        Dish2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Cnt2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        Cnt4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 34)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Maharaja Restuarant");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 430, 36));

        Dish1.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        Dish1.setForeground(new java.awt.Color(255, 255, 255));
        Dish1.setText("Brahmins Thatte Idli ");
        jPanel1.add(Dish1, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 143, -1, 32));

        Price1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        Price1.setForeground(new java.awt.Color(255, 255, 255));
        Price1.setText("35");
        jPanel1.add(Price1, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 191, -1, 25));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Rs.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 191, -1, -1));

        jButton3.setText(" -");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 245, 48, -1));

        Dish3.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        Dish3.setForeground(new java.awt.Color(255, 255, 255));
        Dish3.setText("Veg Kadai ");
        jPanel1.add(Dish3, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 410, -1, 32));

        Price3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        Price3.setForeground(new java.awt.Color(255, 255, 255));
        Price3.setText("70");
        jPanel1.add(Price3, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 468, 32, 25));

        jButton5.setText(" -");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 511, 48, -1));

        Dish4.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        Dish4.setForeground(new java.awt.Color(255, 255, 255));
        Dish4.setText("Gobi Manchurian");
        jPanel1.add(Dish4, new org.netbeans.lib.awtextra.AbsoluteConstraints(787, 410, -1, 32));

        Cnt3.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        Cnt3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Cnt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 511, 30, 29));

        jButton7.setText("+");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 511, 50, -1));

        jButton8.setText(" +");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 245, 50, -1));

        Cnt1.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        Cnt1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Cnt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 245, 37, 29));

        Price2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        Price2.setForeground(new java.awt.Color(255, 255, 255));
        Price2.setText("65");
        jPanel1.add(Price2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 192, 29, -1));

        jButton10.setText(" -");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(787, 250, 48, -1));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mini_project/id1.jpg"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 220, 144));

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mini_project/pv.png"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 143, 210, 144));

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mini_project/vegggi.jpg"))); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 220, 138));

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mini_project/manchu.jpg"))); // NOI18N
        jPanel1.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 410, 210, 138));

        Price4.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        Price4.setForeground(new java.awt.Color(255, 255, 255));
        Price4.setText("110");
        jPanel1.add(Price4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 470, 37, 25));

        jButton17.setText(" -");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(783, 519, 48, -1));

        Dish2.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        Dish2.setForeground(new java.awt.Color(255, 255, 255));
        Dish2.setText("Pav Bhaji");
        jPanel1.add(Dish2, new org.netbeans.lib.awtextra.AbsoluteConstraints(787, 154, 102, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Rs.");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(787, 192, -1, 24));

        Cnt2.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        Cnt2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Cnt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(841, 250, 37, 29));

        jButton1.setText(" +");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(884, 250, 50, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Rs.");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 469, -1, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Rs.");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(787, 472, -1, -1));

        jButton18.setText(" +");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(884, 519, 50, -1));

        Cnt4.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        Cnt4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Cnt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(837, 519, 41, 29));

        jButton4.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        jButton4.setText("NEXT");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 630, -1, -1));

        jButton6.setBackground(new java.awt.Color(51, 51, 51));
        jButton6.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("X");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mini_project/—Pngtree—food menu fare meal background_869492.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
          if(count1<=9)
        {
            count1++;
            Cnt1.setText(""+count1+"");
        }
    }//GEN-LAST:event_jButton8ActionPerformed
     private int count1=0,count2=0,count3=0,count4=0;
    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed
    
    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
         if(count4>=1)
        {
            count4--;
            Cnt4.setText(""+count4+"");
        } 
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
          if(count4<=9)
        {
            count4++;
            Cnt4.setText(""+count4+"");
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         if(count1>=1)
        {
            count1--;
            Cnt1.setText(""+count1+"");
        } 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
          if(count2>=1)
        {
            count2--;
            Cnt2.setText(""+count2+"");
        } 
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
          if(count3>=1)
        {
            count3--;
            Cnt3.setText(""+count3+"");
        } 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         if(count2<=9)
        {
            count2++;
            Cnt2.setText(""+count2+"");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
          if(count3<=9)
        {
            count3++;
            Cnt3.setText(""+count3+"");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(Cnt1.getText().isEmpty() && Cnt2.getText().isEmpty() && Cnt3.getText().isEmpty() && Cnt4.getText().isEmpty() )
        {
           JOptionPane.showMessageDialog(null, "Please select atleast one dish"); 
        }
        else{
        if(update==1)
        {
            new CART_Update(order,"R01",Mn_uname,Dish1.getText(),Cnt1.getText(),Price1.getText(),Dish2.getText(),Cnt2.getText(),Price2.getText(),Dish3.getText(),Cnt3.getText(),Price3.getText(),Dish4.getText(),Cnt4.getText(),Price4.getText()).setVisible(true);
            this.dispose();
        }
        else
        {
            new CART(ord,"R01",Mn_uname,Dish1.getText(),Cnt1.getText(),Price1.getText(),Dish2.getText(),Cnt2.getText(),Price2.getText(),Dish3.getText(),Cnt3.getText(),Price3.getText(),Dish4.getText(),Cnt4.getText(),Price4.getText()).setVisible(true);
            this.dispose();
        }
        }
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cnt1;
    private javax.swing.JLabel Cnt2;
    private javax.swing.JLabel Cnt3;
    private javax.swing.JLabel Cnt4;
    private javax.swing.JLabel Dish1;
    private javax.swing.JLabel Dish2;
    private javax.swing.JLabel Dish3;
    private javax.swing.JLabel Dish4;
    private javax.swing.JLabel Price1;
    private javax.swing.JLabel Price2;
    private javax.swing.JLabel Price3;
    private javax.swing.JLabel Price4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
