/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mini_project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Nayana
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public String unam,ps,pattern;
    //unam=uname.getText();
    public register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        FN = new javax.swing.JLabel();
        LN = new javax.swing.JLabel();
        UN = new javax.swing.JLabel();
        PS = new javax.swing.JLabel();
        CP = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        uname = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        Submit = new javax.swing.JButton();
        pass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        cpass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("REGISTER");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, -10, 380, 110));

        FN.setBackground(new java.awt.Color(0, 0, 0));
        FN.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        FN.setForeground(new java.awt.Color(255, 255, 255));
        FN.setText("First Name");
        jPanel1.add(FN, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 240, 28));

        LN.setBackground(new java.awt.Color(0, 0, 0));
        LN.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        LN.setForeground(new java.awt.Color(255, 255, 255));
        LN.setText("Last Name");
        jPanel1.add(LN, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 200, -1));

        UN.setBackground(new java.awt.Color(0, 0, 0));
        UN.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        UN.setForeground(new java.awt.Color(255, 255, 255));
        UN.setText("Username");
        jPanel1.add(UN, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 250, -1));

        PS.setBackground(new java.awt.Color(0, 0, 0));
        PS.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        PS.setForeground(new java.awt.Color(255, 255, 255));
        PS.setText("Password");
        jPanel1.add(PS, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 230, -1));

        CP.setBackground(new java.awt.Color(0, 0, 0));
        CP.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        CP.setForeground(new java.awt.Color(255, 255, 255));
        CP.setText("Confirm Password");
        jPanel1.add(CP, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 530, 300, -1));

        fname.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fnameKeyTyped(evt);
            }
        });
        jPanel1.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 134, 200, 40));

        lname.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lnameKeyTyped(evt);
            }
        });
        jPanel1.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 224, 200, 40));

        uname.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jPanel1.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 200, 40));

        jButton3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jButton3.setText("LOGIN");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 630, 150, 50));

        Submit.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        Submit.setText("SUBMIT");
        Submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitMouseClicked(evt);
            }
        });
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        jPanel1.add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 630, 170, 50));

        pass.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 430, 200, 40));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, -1, -1));

        cpass.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jPanel1.add(cpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 530, 200, 40));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Have an account?");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 600, 160, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mini_project/619319e00e04d1d9016192b1a9af391f.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 740));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        login el=new login();
        el.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3MouseClicked

    private void SubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitMouseClicked
   
    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        if(fname.getText().isEmpty() || lname.getText().isEmpty() || uname.getText().isEmpty() || pass.getText().isEmpty() || cpass.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please fill all the details");
        }
        
        else
        {
            if(pass.getText().equals(cpass.getText()))
            {
                unam=uname.getText();
                ps=pass.getText();
                pattern = "(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\\S+$).{8,}";
                if(((unam.length()>=5) && (unam.length()<=12)) && ((ps.length()>=5) && (ps.length()<=12)))
                {
                    if(ps.matches(pattern))
                    {
                        try{
                            Class.forName("com.mysql.jdbc.Driver");
                            String query="INSERT INTO register VALUES(?, ?, ?, ?)";
                            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/mini_project", "root","");
                            PreparedStatement pst=con.prepareStatement(query);
                            pst.setString(1, fname.getText());
                            pst.setString(2, lname.getText());
                            pst.setString(3, uname.getText());
                            pst.setString(4, pass.getText());
                            pst.execute();
                            restuarant1 er=new restuarant1(uname.getText());
                            er.setVisible(true);
                            this.dispose();
            
                        }
                        catch(Exception e){
                            JOptionPane.showMessageDialog(null,e);
                        }
                        
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Password should be atleast 8 having atleast one digit,uppercase,lowercase,special characters and no white space");
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Username and Password should be between 5 to 12 characters ");
                }
            
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Password do not match");
            }
        }
           
    }//GEN-LAST:event_SubmitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnameKeyTyped
        // TODO add your handling code here:
        if(!(Character.isLetter(evt.getKeyChar()))){
                evt.consume();
        }
    }//GEN-LAST:event_fnameKeyTyped

    private void lnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnameKeyTyped
        // TODO add your handling code here:
        if(!(Character.isLetter(evt.getKeyChar()))){
                evt.consume();
        }
    }//GEN-LAST:event_lnameKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CP;
    private javax.swing.JLabel FN;
    private javax.swing.JLabel LN;
    private javax.swing.JLabel PS;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel UN;
    private javax.swing.JPasswordField cpass;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lname;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables
}
